stage_1:
  target: stage1.RAE
  params:
    encoder_name: medsiglip-vit-l
    resolution: 256
    decoder_config_path: configs/decoder/ViTXL
    pretrained_decoder_path: null
    noise_tau: 0.0
    normalization_stat_path: null

stage_2:
  target: stage2.models.DDT.DiTwDDTHeadIG
  params:
    input_size: 32
    patch_size:
    - 1
    - 1
    in_channels: 1152
    hidden_size:
    - 1440
    - 2048
    depth:
    - 28
    - 2
    num_heads:
    - 20
    - 16
    mlp_ratio: 4.0
    base_model_depth: 8

conditioning:
  type: label
  cfg_dropout_prob: 0.1
  arch:
    num_t_tokens: 4
    num_c_tokens: 8

transport:
  prediction: x
  time_dist_type: logit-normal_0_1

sampler:
  num_steps: 50

guidance:
  cfg:
    scale: 1.0
    t_min: 0.0
    t_max: 1.0

repa:
  use_repa: true
  repa_layer_depth: 8
  repa_coeff: 0.5
  target_encoder: medsiglip-vit-l
  target_encoder_resolution: 256

dataset:
  target: folder
  data_dir: ../data/BiomedParseDataRAE/train
  condition_type: label
  shared_tmpdir: ~/tmp

training:
  epochs: 80
  global_batch_size: 256
  grad_accum_steps: 2
  ema_decay: 0.9995
  num_workers: 4
  log_interval: 100
  checkpoint_interval: 1
  sample_every: 5000
  clip_grad: 1.0
  global_seed: 42
  optimizer:
    type: gmuon
    lr: 0.0002
    momentum: 0.95
    nesterov: true
    ns_coefficients_preset: POLAR_EXPRESS_COEFFICIENTS
    ns_use_kernels: false
    weight_decay: 0.0
  scheduler:
    type: linear
    warmup_epochs: 25
    decay_end_epoch: 50
    base_lr: 0.0002
    final_lr: 2.0e-05
    warmup_from_zero: false
  image_size: 256

eval:
  eval_interval: 5000
  eval_model: false
  eval_dir: results/medraev2/stage2/eval
  datasets: {}

misc:
  latent_size:
  - 1152
  - 32
  - 32
  num_classes: 28
  time_dist_shift_dim: 1179648
  time_dist_shift_base: 4096
